const labels = {
    tolerance: "Tolerance",
    bed_cm: "Bed Dimensions (cm)",
    print_speed: "Print Speed",
    blade_diameter_in: "Blade Diameter (in)",
    max_blade_speed_rpm: "Max Blade Speed (rpm)",
    bevel_angle_range_deg: "Bevel Angle Range (deg)",
    miter_angle_range_deg: "Miter Angle Range (deg)",
    max_cut_depth_0_deg_bevel_in: "Max Cut Depth - 0° Bevel (in)",
    max_cut_depth_45_deg_bevel_in: "Max Cut Depth - 45° Bevel (in)",
    throat_depth_in: "Throat Depth (in)",
    blade_thickness_in: "Blade Thickness (in)",
    rectangular_cutting_capacity_in: "Rectangular Cutting Capacity (in)",
    bed_in: "Bed Dimensions (in)",
    resolution: "Resolution",
    max_thickness: "Max Thickness",
    operating_modes: "Operating Modes",
    max_thickness_in: "Max Thickness (in)",
    bed_mm: "Bed Dimensions (mm)",
    "print_speed_mm/s": "Print Speed (mm/s)",
    knee_travel_in: "Knee Travel (in)",
    quill_travel_in: "Quill Travel (in)",
    working_area_in: "Working Area (in)",
    throat_distance_in: "Throat Distance (in)",
    x_axis_table_travel_in: "X-Axis Table Travel (in)",
    y_axis_table_travel_in: "Y-Axis Table Travel (in)",
    spindle_speed_range_low_rpm: "Spindle Speed Range - Low (rpm)",
    spindle_speed_range_high_rpm: "Spindle Speed Range - High (rpm)",
    max_speed_rpm: "Max Speed (rpm)",
    min_speed_rpm: "Min Speed (rpm)",
    staff: "Staff",
    shop_mentor: "Shop Mentor",
    shop_manager: "Shop Manager",
    alum: "Alumni",
    student: "Student",
    active: "Active",
    pending: "Pending",
    superseded: "Superseded",
    expired: "Expired",
    revoked: "Revoked",
};

export default labels;